name: Documentation Build
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit tox
      
      - name: Build Documentation
        run: |
          echo "src" >> $GITHUB_PATH
          pip install -r requirements_docs.txt
          make doc html
          touch doc/build/html/.nojekyll
      
      - name: Update HTML Documentation
        uses: actions/upload-artifact@v2
        with:
          name: HTML-Documentation
          path: doc/build/html
          retention-days: 7
