# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: 'Upload to PyPi'
      #if: contains(github.ref, 'refs/tags')
      run: |
          pip install --upgrade pip flit
          pip install -r requirements/requirements_build.txt
          flit build
          pip install twine
          #python setup.py sdist
          twine chek dist/*
          twine upload --skip-existing dist/*
      env:
          TWINE_USERNAME: __token__
          #TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
          TWINE_PASSWORD: ${{secrets.MEDSON_PYPI}}
          TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
